application:  plannit-1136
version: 1
runtime: go
api_version: go1
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 3s
  max_pending_latency: automatic

handlers:
- url: /.*
  script: _go_app
